
log_level = "debug" # (trace -> debug -> info -> warn -> error -> fatal)
collecting_stats_period = "2s"
ping_period = "1s"

# [[aim]]
# name = "local1"
# local_addr = "0.0.0.0:0"
# remote_addr = "0.0.0.0:9000"

# [[aim]]
# name = "local net 1"
# local_addr = "0.0.0.0:0"
# remote_addr = "192.168.8.124:3002"

[[aim]]
name = "local-rust"
local_addr = "0.0.0.0:9001"
remote_addr = "0.0.0.0:9000"
